// ========== MOCK DATA ==========
// All application data is centralized here following the
// Single Responsibility Principle. Data changes happen in one place.

import {
  IconShield,
  IconTools,
  IconBolt,
  IconLightning,
  IconPanel,
  IconBox,
} from "@/components/icons"
import type { Product, Category, Brand, Client, Testimonial } from "./types"

export const categories: Category[] = [
  {
    id: 1,
    name: "Aisladores AT/MT",
    slug: "aisladores",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    subcategories: ["Aisladores de Porcelana", "Aisladores Polimericos", "Aisladores de Vidrio", "Aisladores Pin"],
    count: 186,
    icon: IconShield,
    color: "from-blue-700 to-blue-900",
  },
  {
    id: 2,
    name: "Herrajes de Linea",
    slug: "herrajes",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    subcategories: ["Grapas de Retencion", "Grapas de Suspension", "Preformados", "Amortiguadores"],
    count: 245,
    icon: IconTools,
    color: "from-slate-600 to-slate-800",
  },
  {
    id: 3,
    name: "Conectores de Potencia",
    slug: "conectores",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    subcategories: ["Conectores a Compresion", "Conectores Mecanicos", "Terminales AT", "Empalmes"],
    count: 198,
    icon: IconBolt,
    color: "from-red-700 to-red-900",
  },
  {
    id: 4,
    name: "Cables AT/MT",
    slug: "cables",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
    subcategories: ["Cable XLPE", "Cable EPR", "Cable Aereo AAAC", "Cable de Guarda OPGW"],
    count: 134,
    icon: IconLightning,
    color: "from-blue-600 to-indigo-800",
  },
  {
    id: 5,
    name: "Transformadores",
    slug: "transformadores",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    subcategories: ["Transformadores de Distribucion", "Transformadores de Corriente", "Transformadores de Potencial", "Seccionadores"],
    count: 87,
    icon: IconPanel,
    color: "from-emerald-700 to-emerald-900",
  },
  {
    id: 6,
    name: "Ferreteria Electrica",
    slug: "ferreteria",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=800&q=80",
    subcategories: ["Pernos y Tuercas", "Abrazaderas", "Crucetas", "Postes y Estructuras"],
    count: 312,
    icon: IconBox,
    color: "from-zinc-600 to-zinc-800",
  },
  {
    id: 7,
    name: "Celdas de Media Tension",
    slug: "celdas",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    subcategories: ["Celdas Metal-Clad", "Celdas de Remonte", "Celdas de Medida", "Celdas de Proteccion"],
    count: 45,
    icon: IconPanel,
    color: "from-blue-700 to-indigo-900",
  },
  {
    id: 8,
    name: "Pararrayos y Descargadores",
    slug: "pararrayos",
    image: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=600&q=80",
    subcategories: ["Pararrayos Polimericos 10kV", "Pararrayos 22.9kV", "Pararrayos 60kV", "Contadores de Descargas"],
    count: 120,
    icon: IconShield,
    color: "from-red-600 to-red-800",
  },
  {
    id: 9,
    name: "Seccionadores",
    slug: "seccionadores",
    image: "https://images.unsplash.com/photo-1581092921461-7031e4bf0e29?w=600&q=80",
    subcategories: ["Seccionadores Tripolares", "Seccionadores Unipolares", "Seccionadores Bajo Carga", "Cuchillas de Tierra"],
    count: 88,
    icon: IconBolt,
    color: "from-emerald-600 to-emerald-800",
  },
  {
    id: 10,
    name: "Iluminacion Industrial",
    slug: "iluminacion",
    image: "https://images.unsplash.com/photo-1517650862521-d580d5348145?w=600&q=80",
    subcategories: ["Luminarias LED Viales", "Reflectores Alta Potencia", "Iluminacion Antiexplosiva", "Postes de Iluminacion"],
    count: 215,
    icon: IconLightning,
    color: "from-amber-500 to-orange-700",
  },
  {
    id: 11,
    name: "Reclosers (Reconectadores)",
    slug: "reclosers",
    image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600&q=80",
    subcategories: ["Reconectadores Trifasicos", "Reconectadores Monofasicos", "Gabinetes de Control", "Accesorios"],
    count: 32,
    icon: IconPanel,
    color: "from-slate-700 to-slate-900",
  },
  {
    id: 12,
    name: "Puestas a Tierra (PAT)",
    slug: "pat",
    image: "https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?w=600&q=80",
    subcategories: ["Varillas Copperweld", "Soldadura Exotermica", "Cables de Cobre Desnudo", "Conectores PAT"],
    count: 156,
    icon: IconTools,
    color: "from-amber-700 to-yellow-900",
  },
  {
    id: 13,
    name: "Medicion y Monitoreo",
    slug: "medicion",
    image: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=600&q=80",
    subcategories: ["Medidores Multifuncion", "Transformadores de Medida", "Analizadores de Redes", "Sistemas SCADA"],
    count: 74,
    icon: IconBox,
    color: "from-cyan-600 to-blue-800",
  },
  {
    id: 14,
    name: "Herramientas Vivas (TCT)",
    slug: "herramientas",
    image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&q=80",
    subcategories: ["Pertigas Telescopicas", "Equipos de Puesta a Tierra Temporales", "Detectores de Tension", "Mantas Aislantes"],
    count: 190,
    icon: IconShield,
    color: "from-red-500 to-red-700",
  },
  {
    id: 15,
    name: "Tableros Electricos",
    slug: "tableros",
    image: "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=600&q=80",
    subcategories: ["Tableros Autosoportados", "Tableros Adosables", "Tableros de Transferencia", "Centro de Control de Motores"],
    count: 105,
    icon: IconPanel,
    color: "from-slate-600 to-zinc-800",
  },
  {
    id: 16,
    name: "Mufas y Empalmes",
    slug: "mufas",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    subcategories: ["Terminaciones Termocontractiles", "Empalmes en Frío", "Manguitos", "Cintas Aislantes AT"],
    count: 143,
    icon: IconBolt,
    color: "from-zinc-700 to-zinc-900",
  },
]

export const products: Product[] = [
  {
    id: 1,
    sku: "AIS-POR-001",
    name: "Aislador de Porcelana Tipo Pin 25kV Clase ANSI 56-2",
    brand: "NGK",
    category: "Aisladores AT/MT",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80",
    specs: ["25kV", "ANSI 56-2", "Porcelana", "Clase B"],
    description: "Aislador tipo pin de porcelana para lineas de media tension hasta 25kV.",
    fullDescription: "Aislador de porcelana vitrificada tipo pin disenado para lineas de distribucion y subtransmision hasta 25kV. Fabricado con porcelana de alta resistencia mecanica y electrica, con glaseado marron resistente a la intemperie. Cumple normas ANSI C29.6.",
    technicalSpecs: [
      { label: "Tension Nominal", value: "25 kV" },
      { label: "Clase ANSI", value: "56-2" },
      { label: "Material", value: "Porcelana Vitrificada" },
      { label: "Distancia de Fuga", value: "430 mm" },
      { label: "Carga de Rotura", value: "11 kN" },
      { label: "Norma", value: "ANSI C29.6" },
      { label: "Peso", value: "3.8 kg" },
      { label: "Aplicacion", value: "Lineas MT 15-25kV" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80",
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
    ],
    featured: true,
    bestSeller: true,
    rating: 4.9,
  },
  {
    id: 2,
    sku: "HRJ-GRP-002",
    name: "Grapa de Retencion para Cable AAAC 120mm2",
    brand: "Sicame",
    category: "Herrajes de Linea",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
    specs: ["120mm2", "Aluminio", "35kN", "Tipo NFC"],
    description: "Grapa de retencion preformada para conductor AAAC de 120mm2.",
    fullDescription: "Grapa de retencion tipo preformado disenada para sujetar conductores AAAC de aleacion de aluminio de 120mm2 en postes de anclaje. Fabricada en aleacion de aluminio de alta resistencia a la corrosion.",
    technicalSpecs: [
      { label: "Seccion", value: "120 mm2" },
      { label: "Material", value: "Aleacion de Aluminio" },
      { label: "Carga de Rotura", value: "35 kN" },
      { label: "Tipo", value: "NFC 33-040" },
      { label: "Norma", value: "IEC 61284" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
    ],
    featured: true,
    bestSeller: true,
    rating: 4.7,
  },
  {
    id: 3,
    sku: "CON-COM-003",
    name: "Conector a Compresion Bimetalico Cu-Al 240mm2",
    brand: "Burndy",
    category: "Conectores de Potencia",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    specs: ["240mm2", "Cu-Al", "36kV", "IEC 61238"],
    description: "Conector bimetalico cobre-aluminio para empalmes y derivaciones en alta tension.",
    fullDescription: "Conector tipo compresion bimetalico para union de conductores de cobre y aluminio en sistemas de alta y media tension. Fabricado con barril de aluminio y punta de cobre estanado.",
    technicalSpecs: [
      { label: "Seccion", value: "240 mm2" },
      { label: "Material", value: "Bimetalico Cu-Al" },
      { label: "Tension", value: "36 kV" },
      { label: "Norma", value: "IEC 61238" },
      { label: "Tipo", value: "Compresion Hexagonal" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
    featured: true,
    bestSeller: true,
    rating: 4.8,
  },
  {
    id: 4,
    sku: "CBL-XLPE-004",
    name: "Cable XLPE 15kV 1/0 AWG Monopolar",
    brand: "Nexans",
    category: "Cables AT/MT",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    specs: ["15kV", "1/0 AWG", "XLPE", "133%"],
    description: "Cable de media tension con aislamiento XLPE para redes subterraneas.",
    fullDescription: "Cable monopolar de media tension con conductor de cobre o aluminio, aislamiento de polietileno reticulado (XLPE), pantalla semiconductora y cubierta exterior de PVC. Para redes subterraneas de 15kV.",
    technicalSpecs: [
      { label: "Tension", value: "15 kV" },
      { label: "Calibre", value: "1/0 AWG" },
      { label: "Aislamiento", value: "XLPE 133%" },
      { label: "Pantalla", value: "Cinta Semiconductora" },
      { label: "Norma", value: "NTP 370.252" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    ],
    featured: true,
    bestSeller: true,
    rating: 4.8,
  },
  {
    id: 5,
    sku: "TRF-DST-005",
    name: "Transformador de Distribucion 250kVA 22.9/0.4kV",
    brand: "ABB",
    category: "Transformadores",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    specs: ["250kVA", "22.9kV", "Aceite", "Trifasico"],
    description: "Transformador trifasico de distribucion en bano de aceite para subestaciones.",
    fullDescription: "Transformador de distribucion trifasico sumergido en aceite mineral con aislamiento clase A. Nucleo de acero al silicio de grano orientado. Tanque hermetico con radiadores. Para uso en subestaciones aereas y de pedestal.",
    technicalSpecs: [
      { label: "Potencia", value: "250 kVA" },
      { label: "Tension Primaria", value: "22.9 kV" },
      { label: "Tension Secundaria", value: "0.4 kV" },
      { label: "Fases", value: "Trifasico" },
      { label: "Refrigerante", value: "Aceite Mineral" },
      { label: "Norma", value: "IEC 60076" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.9,
  },
  {
    id: 6,
    sku: "FER-CRU-006",
    name: "Cruceta de Acero Galvanizado 2.4m Tipo L75x75x6mm",
    brand: "Prodac",
    category: "Ferreteria Electrica",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&q=80",
    specs: ["2.4m", "Galvanizado", "L75x75x6", "800kg"],
    description: "Cruceta metalica de acero galvanizado en caliente para postes de concreto.",
    fullDescription: "Cruceta fabricada en perfil de acero angular L75x75x6mm galvanizado por inmersion en caliente. Para montaje de aisladores y herrajes en lineas de media tension aereas.",
    technicalSpecs: [
      { label: "Longitud", value: "2.4 m" },
      { label: "Perfil", value: "L75x75x6 mm" },
      { label: "Material", value: "Acero A36" },
      { label: "Recubrimiento", value: "Galvanizado en Caliente" },
      { label: "Carga", value: "800 kg" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&q=80",
    ],
    featured: true,
    bestSeller: true,
    rating: 4.6,
  },
  {
    id: 7,
    sku: "AIS-POL-007",
    name: "Aislador Polimerico de Suspension 36kV",
    brand: "Sediver",
    category: "Aisladores AT/MT",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80",
    specs: ["36kV", "Polimerico", "120kN", "IEC 61109"],
    description: "Aislador polimerico de suspension para lineas de alta tension.",
    fullDescription: "Aislador de suspension tipo polimerico con nucleo de fibra de vidrio y aletas de goma silicona. Alta resistencia a la contaminacion y menor peso que aisladores de vidrio.",
    technicalSpecs: [
      { label: "Tension", value: "36 kV" },
      { label: "Carga Mecanica", value: "120 kN" },
      { label: "Material", value: "Silicona/FRP" },
      { label: "Norma", value: "IEC 61109" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.7,
  },
  {
    id: 8,
    sku: "HRJ-AMR-008",
    name: "Amortiguador de Vibraciones Stockbridge",
    brand: "PLP",
    category: "Herrajes de Linea",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
    specs: ["AAAC 120mm2", "Stockbridge", "Aluminio", "IEC 61897"],
    description: "Amortiguador tipo Stockbridge para proteccion contra vibraciones eolicas.",
    fullDescription: "Amortiguador de vibraciones tipo Stockbridge para conductores electricos aereos. Protege al conductor de fatiga por vibracion eolica.",
    technicalSpecs: [
      { label: "Conductor", value: "AAAC 120mm2" },
      { label: "Tipo", value: "Stockbridge" },
      { label: "Frecuencia", value: "10-60 Hz" },
      { label: "Norma", value: "IEC 61897" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.5,
  },
  {
    id: 9,
    sku: "CON-TER-009",
    name: "Terminal Exterior 15kV para Cable XLPE",
    brand: "3M",
    category: "Conectores de Potencia",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    specs: ["15kV", "Termocontractil", "Interior/Exterior", "IEC 60502"],
    description: "Terminal termocontractil para cable de media tension XLPE.",
    fullDescription: "Terminal de cable de media tension tipo termocontractil para terminacion de cables con aislamiento XLPE. Kit completo con tubo de control de campo.",
    technicalSpecs: [
      { label: "Tension", value: "15 kV" },
      { label: "Tipo", value: "Termocontractil" },
      { label: "Aplicacion", value: "Interior/Exterior" },
      { label: "Norma", value: "IEC 60502" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.6,
  },
  {
    id: 10,
    sku: "CBL-AAC-010",
    name: "Cable Aereo AAAC 120mm2 Aleacion 6201",
    brand: "Nexans",
    category: "Cables AT/MT",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    specs: ["120mm2", "AAAC", "6201-T81", "IEC 61089"],
    description: "Conductor aereo de aleacion de aluminio para lineas de transmision y distribucion.",
    fullDescription: "Conductor aereo desnudo de aleacion de aluminio 6201-T81 para lineas de transmision y distribucion. Alta resistencia mecanica y buena conductividad electrica.",
    technicalSpecs: [
      { label: "Seccion", value: "120 mm2" },
      { label: "Aleacion", value: "6201-T81" },
      { label: "Resistencia", value: "0.268 ohm/km" },
      { label: "Carga Rotura", value: "37.8 kN" },
      { label: "Norma", value: "IEC 61089" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.5,
  },
  {
    id: 11,
    sku: "TRF-COR-011",
    name: "Transformador de Corriente 200/5A Clase 0.5",
    brand: "ABB",
    category: "Transformadores",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    specs: ["200/5A", "Clase 0.5", "36kV", "Exterior"],
    description: "Transformador de medida de corriente para subestaciones de alta tension.",
    fullDescription: "Transformador de corriente tipo ventana para medicion y proteccion en subestaciones de alta y media tension. Nucleo de acero al silicio de alta permeabilidad.",
    technicalSpecs: [
      { label: "Relacion", value: "200/5 A" },
      { label: "Clase", value: "0.5" },
      { label: "Tension", value: "36 kV" },
      { label: "Aplicacion", value: "Exterior" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.8,
  },
  {
    id: 12,
    sku: "FER-PER-012",
    name: "Perno de Maquina Galvanizado 5/8 x 10\" Grado 5",
    brand: "Prodac",
    category: "Ferreteria Electrica",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&q=80",
    specs: ["5/8\"", "10 pulg", "Grado 5", "Galvanizado"],
    description: "Perno de maquina para montaje de crucetas y herrajes en postes.",
    fullDescription: "Perno de maquina con rosca completa grado 5 galvanizado en caliente incluye tuerca y arandela. Para fijacion de herrajes, crucetas y accesorios en postes de concreto y madera.",
    technicalSpecs: [
      { label: "Diametro", value: "5/8\"" },
      { label: "Longitud", value: "10 pulg" },
      { label: "Grado", value: "5" },
      { label: "Recubrimiento", value: "Galvanizado en Caliente" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&q=80",
    ],
    featured: false,
    bestSeller: false,
    rating: 4.4,
  },
]

export const brands: Brand[] = [
  { name: "ABB", logo: "https://logo.clearbit.com/abb.com" },
  { name: "Siemens", logo: "https://logo.clearbit.com/siemens.com" },
  { name: "Schneider", logo: "https://logo.clearbit.com/se.com" },
  { name: "3M", logo: "https://logo.clearbit.com/3m.com" },
  { name: "Nexans", logo: "https://logo.clearbit.com/nexans.com" },
  { name: "Burndy", logo: "https://logo.clearbit.com/burndy.com" },
  { name: "Sicame", logo: "https://logo.clearbit.com/sicame.com" },
  { name: "NGK", logo: "https://logo.clearbit.com/ngk.de" },
  { name: "Sediver", logo: "https://logo.clearbit.com/sediver.com" },
  { name: "PLP", logo: "https://logo.clearbit.com/plp.com" },
  { name: "Hubbell", logo: "https://logo.clearbit.com/hubbell.com" },
  { name: "Eaton", logo: "https://logo.clearbit.com/eaton.com" },
]

export const clients: Client[] = [
  { name: "Enel Peru", logo: "https://logo.clearbit.com/enel.pe" },
  { name: "Luz del Sur", logo: "https://logo.clearbit.com/luzdelsur.com.pe" },
  { name: "Electrocentro", logo: "https://logo.clearbit.com/distriluz.com.pe" },
  { name: "Hidrandina", logo: "https://logo.clearbit.com/distriluz.com.pe" },
  { name: "SEAL Arequipa", logo: "https://logo.clearbit.com/seal.com.pe" },
  { name: "Electro Oriente", logo: "https://logo.clearbit.com/electrooriente.com.pe" },
  { name: "Red Electrica", logo: "https://logo.clearbit.com/ree.es" },
  { name: "ISA REP", logo: "https://logo.clearbit.com/isa.com.co" },
  { name: "Consorcio Trans.", logo: "https://logo.clearbit.com/ctm.com.pe" },
  { name: "Antamina", logo: "https://logo.clearbit.com/antamina.com" },
  { name: "Southern Peru", logo: "https://logo.clearbit.com/southerncoppercorp.com" },
  { name: "Cerro Verde", logo: "https://logo.clearbit.com/cerroverde.pe" },
]

export const testimonials: Testimonial[] = [
  {
    id: 1,
    text: "Electro Thina nos ha suministrado aisladores y herrajes de linea para nuestros proyectos de electrificacion rural con un nivel de calidad y cumplimiento excepcional.",
    author: "Ing. Carlos Mendoza",
    position: "Jefe de Proyectos AT/MT",
    company: "Enel Distribucion",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
  {
    id: 2,
    text: "La asesoria tecnica en seleccion de cables XLPE y conectores para nuestra subestacion fue fundamental. Profesionalismo y experiencia en cada detalle.",
    author: "Ing. Maria Garcia",
    position: "Gerente de Ingenieria",
    company: "Luz del Sur",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: 3,
    text: "Proveedor confiable de ferreteria electrica y transformadores. Sus tiempos de entrega y stock permanente nos permiten mantener nuestras operaciones sin interrupciones.",
    author: "Ing. Roberto Sanchez",
    position: "Director de Compras",
    company: "Electrocentro",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
]
